### ISSUE TITLE
Refusing to install exclusive-keyboard as a dependency of itself

### ISSUE THREAD

**Issue by martinszeltins** [pfirpfel/node-exclusive-keyboard#2]
Error when installing

````
npm ERR! Linux 4.15.0-74-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "exclusive-keyboard"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF
 
npm ERR! Refusing to install exclusive-keyboard as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
 
npm ERR! Please include the following file with any support request:
npm ERR!     /home/martins/Documents/exclusive-keyboard/npm-debug.log
````

npm-debug.log

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'exclusive-keyboard' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData exclusive-keyboard
8 silly fetchNamedPackageData exclusive-keyboard
9 silly mapToRegistry name exclusive-keyboard
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/exclusive-keyboard
13 verbose request uri https://registry.npmjs.org/exclusive-keyboard
14 verbose request no auth needed
15 info attempt registry request try #1 at 4:41:16 PM
16 verbose request id 44dc0026b34cc071
17 verbose etag W/"e11fe36881ecd3bd3f48b3727eb64846"
18 verbose lastModified Sun, 28 Jul 2019 12:55:19 GMT
19 http request GET https://registry.npmjs.org/exclusive-keyboard
20 http 304 https://registry.npmjs.org/exclusive-keyboard
21 verbose headers { date: 'Tue, 21 Jan 2020 14:41:16 GMT',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'set-cookie':
21 verbose headers    [ '__cfduid=db8f7056aef7bcf361f4ab8171ade30271579617676; expires=Thu, 20-Feb-20 14:41:16 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
21 verbose headers   'cf-ray': '558a0c50e829b4ae-RIX',
21 verbose headers   age: '27',
21 verbose headers   'cache-control': 'public, max-age=300',
21 verbose headers   etag: '"e11fe36881ecd3bd3f48b3727eb64846"',
21 verbose headers   'last-modified': 'Sun, 28 Jul 2019 12:55:19 GMT',
21 verbose headers   vary: 'Accept-Encoding',
21 verbose headers   'cf-cache-status': 'HIT',
21 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
21 verbose headers   server: 'cloudflare' }
22 silly get cb [ 304,
22 silly get   { date: 'Tue, 21 Jan 2020 14:41:16 GMT',
22 silly get     connection: 'keep-alive',
22 silly get     'set-cookie':
22 silly get      [ '__cfduid=db8f7056aef7bcf361f4ab8171ade30271579617676; expires=Thu, 20-Feb-20 14:41:16 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
22 silly get     'cf-ray': '558a0c50e829b4ae-RIX',
22 silly get     age: '27',
22 silly get     'cache-control': 'public, max-age=300',
22 silly get     etag: '"e11fe36881ecd3bd3f48b3727eb64846"',
22 silly get     'last-modified': 'Sun, 28 Jul 2019 12:55:19 GMT',
22 silly get     vary: 'Accept-Encoding',
22 silly get     'cf-cache-status': 'HIT',
22 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 silly get     server: 'cloudflare' } ]
23 verbose etag https://registry.npmjs.org/exclusive-keyboard from cache
24 verbose get saving exclusive-keyboard to /home/martins/.npm/registry.npmjs.org/exclusive-keyboard/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install exclusive-keyboard as a dependency of itself
42 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (<anonymous>)
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (<anonymous>)
42 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
43 verbose cwd /home/martins/Documents/exclusive-keyboard
44 error Linux 4.15.0-74-generic
45 error argv "/usr/bin/node" "/usr/bin/npm" "i" "exclusive-keyboard"
46 error node v8.10.0
47 error npm  v3.5.2
48 error code ENOSELF
49 error Refusing to install exclusive-keyboard as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]
````

**Comment by pfirpfel** [comment]
If you check out this repository and then try to install the module inside the checked out repository, the installation will fail.
